# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popeye.ui'
#
# Created: Tue Jan 28 15:18:07 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(809, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(809, 604))
        MainWindow.setMaximumSize(QtCore.QSize(809, 604))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("border-style: none;\n"
"background-position: top right;\n"
"\n"
""))
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(809, 555))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setStyleSheet(_fromUtf8("background: transparent; border: transparent"))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setWhatsThis(_fromUtf8(""))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/run.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/others.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem = QtGui.QSpacerItem(326, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox)
        self.pushButton_6.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad_Images = QtGui.QMenu(self.menuFile)
        self.menuLoad_Images.setObjectName(_fromUtf8("menuLoad_Images"))
        self.menuExport_to = QtGui.QMenu(self.menuFile)
        self.menuExport_to.setObjectName(_fromUtf8("menuExport_to"))
        self.menuModules = QtGui.QMenu(self.menuBar)
        self.menuModules.setObjectName(_fromUtf8("menuModules"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionLoad_Project = QtGui.QAction(MainWindow)
        self.actionLoad_Project.setObjectName(_fromUtf8("actionLoad_Project"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionBatch_Mode = QtGui.QAction(MainWindow)
        self.actionBatch_Mode.setObjectName(_fromUtf8("actionBatch_Mode"))
        self.actionInteractive_Mode = QtGui.QAction(MainWindow)
        self.actionInteractive_Mode.setObjectName(_fromUtf8("actionInteractive_Mode"))
        self.actionTPS_file = QtGui.QAction(MainWindow)
        self.actionTPS_file.setObjectName(_fromUtf8("actionTPS_file"))
        self.actionMorphoJ_file = QtGui.QAction(MainWindow)
        self.actionMorphoJ_file.setObjectName(_fromUtf8("actionMorphoJ_file"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXls = QtGui.QAction(MainWindow)
        self.actionXls.setObjectName(_fromUtf8("actionXls"))
        self.actionTxt = QtGui.QAction(MainWindow)
        self.actionTxt.setObjectName(_fromUtf8("actionTxt"))
        self.actionAge_Estimation = QtGui.QAction(MainWindow)
        self.actionAge_Estimation.setObjectName(_fromUtf8("actionAge_Estimation"))
        self.actionSex_Estimation = QtGui.QAction(MainWindow)
        self.actionSex_Estimation.setObjectName(_fromUtf8("actionSex_Estimation"))
        self.actionEye_Color_Estimation = QtGui.QAction(MainWindow)
        self.actionEye_Color_Estimation.setObjectName(_fromUtf8("actionEye_Color_Estimation"))
        self.actionSkin_Color_Estimation = QtGui.QAction(MainWindow)
        self.actionSkin_Color_Estimation.setObjectName(_fromUtf8("actionSkin_Color_Estimation"))
        self.actionManual_Landmarking = QtGui.QAction(MainWindow)
        self.actionManual_Landmarking.setObjectName(_fromUtf8("actionManual_Landmarking"))
        self.actionReport_Generation = QtGui.QAction(MainWindow)
        self.actionReport_Generation.setObjectName(_fromUtf8("actionReport_Generation"))
        self.actionLandmark_Configuration = QtGui.QAction(MainWindow)
        self.actionLandmark_Configuration.setObjectName(_fromUtf8("actionLandmark_Configuration"))
        self.action3D_Reconstruction = QtGui.QAction(MainWindow)
        self.action3D_Reconstruction.setObjectName(_fromUtf8("action3D_Reconstruction"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.menuLoad_Images.addAction(self.actionBatch_Mode)
        self.menuLoad_Images.addAction(self.actionInteractive_Mode)
        self.menuExport_to.addAction(self.actionTPS_file)
        self.menuExport_to.addAction(self.actionMorphoJ_file)
        self.menuExport_to.addAction(self.actionCSV)
        self.menuExport_to.addAction(self.actionXls)
        self.menuExport_to.addAction(self.actionTxt)
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLoad_Images.menuAction())
        self.menuFile.addAction(self.menuExport_to.menuAction())
        self.menuModules.addAction(self.actionAge_Estimation)
        self.menuModules.addAction(self.actionSex_Estimation)
        self.menuModules.addAction(self.actionEye_Color_Estimation)
        self.menuModules.addAction(self.actionSkin_Color_Estimation)
        self.menuTools.addAction(self.actionManual_Landmarking)
        self.menuTools.addAction(self.actionReport_Generation)
        self.menuTools.addAction(self.actionLandmark_Configuration)
        self.menuTools.addAction(self.action3D_Reconstruction)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuModules.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PopEye", None))
        self.pushButton.setToolTip(_translate("MainWindow", "Agregar Imagenes ...", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Preferencias de Extracción de Landmarks ...", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Extraer Landmarks ...", None))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Guardar Resultados ...", None))
        self.pushButton_6.setToolTip(_translate("MainWindow", "Información ...", None))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Salir ...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuLoad_Images.setTitle(_translate("MainWindow", "Load Images", None))
        self.menuExport_to.setTitle(_translate("MainWindow", "Export to ..", None))
        self.menuModules.setTitle(_translate("MainWindow", "Modules", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project", None))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project", None))
        self.actionBatch_Mode.setText(_translate("MainWindow", "Batch Mode", None))
        self.actionInteractive_Mode.setText(_translate("MainWindow", "Interactive Mode", None))
        self.actionTPS_file.setText(_translate("MainWindow", "TPS file", None))
        self.actionMorphoJ_file.setText(_translate("MainWindow", "MorphoJ file", None))
        self.actionCSV.setText(_translate("MainWindow", "CVS", None))
        self.actionXls.setText(_translate("MainWindow", "XLS", None))
        self.actionTxt.setText(_translate("MainWindow", "TXT", None))
        self.actionAge_Estimation.setText(_translate("MainWindow", "Age Estimation", None))
        self.actionSex_Estimation.setText(_translate("MainWindow", "Sex Estimation", None))
        self.actionEye_Color_Estimation.setText(_translate("MainWindow", "Eye Color Estimation", None))
        self.actionSkin_Color_Estimation.setText(_translate("MainWindow", "Skin Color Estimation", None))
        self.actionManual_Landmarking.setText(_translate("MainWindow", "Manual Landmarking", None))
        self.actionReport_Generation.setText(_translate("MainWindow", "Report Generation", None))
        self.actionLandmark_Configuration.setText(_translate("MainWindow", "Landmark Configuration", None))
        self.action3D_Reconstruction.setText(_translate("MainWindow", "3D Reconstruction", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))

import Icons_rc
